#!/usr/bin/env bash
set -euo pipefail

: "${MARIADB_ROOT_PASSWORD:?MARIADB_ROOT_PASSWORD is required}"
: "${MARIADB_USER:?MARIADB_USER is required}"
: "${MARIADB_TEST_DATABASE:?MARIADB_TEST_DATABASE is required}"

mariadb --protocol=socket -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${MARIADB_TEST_DATABASE}\`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON \`${MARIADB_TEST_DATABASE}\`.*
    TO '${MARIADB_USER}'@'%';

FLUSH PRIVILEGES;
SQL
